import './globals.css'
import { Sen } from 'next/font/google'
import { NavBar } from '@/components/NavBar/page';
import { Footer } from '@/components/Footer/page';
import DisableComponent from '@/HOC/DisableComponent';
import ReduxProvider from '@/redux/provider';

const sen = Sen({ subsets: ['latin'] })

export const metadata = {
  title: 'Moteros',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      </head>
      <ReduxProvider>
        <body className={sen.className}>
          <DisableComponent disablePaths={['/login', '/register']}>
            <header>
              <NavBar/>
            </header>
          </DisableComponent>
          {children}

          <DisableComponent disablePaths={['/login', '/register']}>
            <Footer/>
          </DisableComponent>
          </body>
      </ReduxProvider>
    </html>
  )
}
