import './globals.css'
import { Sen } from 'next/font/google'

const sen = Sen({ subsets: ['latin'] })

export const metadata = {
  title: 'Moteros',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sen.className}>{children}</body>
    </html>
  )
}
