import './globals.css'
import { Sen } from 'next/font/google'
import { NavBar } from '@/components/NavBar/page';
// import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { Footer } from '@/components/Footer/page';
import DisableComponent from '@/HOC/DisableComponent';

const sen = Sen({ subsets: ['latin'] })

export const metadata = {
  title: 'Moteros',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={sen.className}>
        <DisableComponent disablePaths={['/login', '/register', '/login-Password', '/login-register-password']}>
          <header>
            <NavBar/>
          </header>
        </DisableComponent>
        {children}

        <DisableComponent disablePaths={['/login', '/register', '/login-Password', '/login-register-password']}>
          <Footer/>
        </DisableComponent>
        </body>
    </html>
  )
}
